### ISSUE TITLE
Exclusive Canonicalization handles entities improperly which causes invalid digests

### ISSUE THREAD

**Issue by Buzer** [yaronn/xml-crypto#28]
The problem came up when I had " as part of the node's text, it was being translated to \&quot;. However, according to the spec, it should only be replaced when used in attribute's value, not text. 

http://www.w3.org/TR/2001/REC-xml-c14n-20010315#Example-Chars

It also seems that attributes use incomplete list of allowed entities (missing \&#xA; and \&#x9;).

**Comment by renatoargh** [comment]
I am having the opposite problem; whem I pass `&quot;` as a nodes value it comes out (after signing) as a regular `"` breaking signature :/

To reproduce; https://tonicdev.com/renatoargh/569eed41c4e01c0d005a3327 (expand the results and click `Full Text`)

Any ideas?

**Comment by yaronn** [comment]
does it work if you use getSignatureXml() instead of getSignedXml() and construct the final result yourself? what if you use &amp;quot;? I think it might be an issue with the xmldom dependency, you can verify by loading some xml with quote to it and then run toString() on the node.

**Comment by marklagendijk** [comment]
I ran into the same issue and found the cause. The ExclusiveCanonicalization replaces certain characters with entity references. 
The problem is that it uses the same replacement maps for attributes and text. This is [wrong](https://www.w3.org/2008/xmlsec/Drafts/c14n-20/test-cases/#sec-Example-Chars):

> Encoding of special characters as character references in attribute values (&amp;, &lt;, &quot;, &#xD;, &#xA;, &#x9;)
> Encoding of special characters as character references in text (&amp;, &lt;, &gt;, &#xD;)

The solution would be to create separate normalizing functions for normalizing attribute values and text.
