### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by siacomuzzi** [yaronn/xml-crypto#83]
could you please publish a new version including latest 2 commits?

Thanks!

**Comment by bjrmatos** [comment]
any use case for that? it is just a refactor of the [this commit](https://github.com/yaronn/xml-crypto/commit/50824066c56b8ad2e6a64c76810de53888e07cee) and we'll probably remove that code because it is supporting malformed xml. see this thread for [more information](https://github.com/yaronn/xml-crypto/pull/82).

but i'm curious if you're relying on this behaviour for something in particular

**Comment by bjrmatos** [comment]
also, i will take the opportunity to ask.. would you like to join efforts with us? i ask this because i've noticed that you guys (the auth0 team) [have a fork of xml-crypto](https://github.com/auth0/xml-crypto), i've seen other libraries relying on that fork and i think this is bad, we're just duplicating efforts and really the auth0 fork only have some commits different to the main repo.

would you like to tell us about why you guys have decided to fork xml-crypto? so we can fix it and maintain only one repository for the good of all.

cc @yaronn

**Comment by siacomuzzi** [comment]
> any use case for that? it is just a refactor of this commit and we'll probably remove that code because it is supporting malformed xml.

Cool, I think I'm OK with the [specified commit](https://github.com/yaronn/xml-crypto/commit/50824066c56b8ad2e6a64c76810de53888e07cee).

> also, i will take the opportunity to ask.. would you like to join efforts with us? i ask this because i've noticed that you guys (the auth0 team) have a fork of xml-crypto...

That would be great. If you are OK, I can send you a PR with the following changes:

* https://github.com/auth0/xml-crypto/commit/72a56c44a633f3560c7e045f9433e3208117aa63
* https://github.com/auth0/xml-crypto/commit/55296d32cd523d597a403039cac7a58383485e75

And the tricky one (maybe you found a better solution, it's related to https://github.com/yaronn/xml-crypto/issues/48, https://github.com/yaronn/xml-crypto/issues/60 and https://github.com/yaronn/xml-crypto/issues/72):

* https://github.com/auth0/xml-crypto/commit/25a3d1c00fd0751530f7a06f7219c6eb6860412d

**Comment by bjrmatos** [comment]
cool!, unfourtanly i have no experience with `InclusiveNamespaces` so we'll need the help of @yaronn here.

@yaronn [the workaround](https://github.com/auth0/xml-crypto/commit/25a3d1c00fd0751530f7a06f7219c6eb6860412d) looks good to you? how it can be less tricky?

**Comment by yaronn** [comment]
It would be great to join efforts, really like the idea!

As for the workaround - I think another approach could be to have this code inside the canonization class such that the class is aware of the inclusive namespaces and can embed them on the right element in a generic manner (not just a fixed list of nodes). There shouldn't be a need to wait for the failure of the initial validation since we can tell up front there are namespaces to include. I think for now we can merge the workaround and open a task for later. Also would be great to have a unit test on this.

Anyway this issue did repeat in several posts so great to include a solution for it.

**Comment by LoneRifle** [comment]
Closing this for now. The commits cited in this issue have either been implemented independently or merged through other means (as is the case of #172)
